# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mental flow
email: zhou.dong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Physicist turned into programmer. Past experience includes crystallography, medical imaging, quantum computing, etc. <br>
  A reader and writer. Interested in martial arts, yoga, and other ancient teachings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nosarthur.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  nosarthur

# Build settings
markdown: kramdown
highlighter: rouge
future: False
